language: go

services:
  - docker

dist: trusty

go:
  - "tip"

env:
  global:
    - IMAGINARY_VERSION="${TRAVIS_TAG:-dev}"
  matrix:
    - LIBVIPS=8.7.2 GOVER=latest
    - LIBVIPS=8.7.3 GOVER=latest
    - LIBVIPS=8.7.4 GOVER=latest
    - LIBVIPS=8.7.4 GOVER=rc
    - LIBVIPS=8.7.4 GOVER=1.10

matrix:
  allow_failures:
    - env: LIBVIPS=8.7.2
    - env: GOVER=rc

before_install:
  - docker pull h2non/imaginary:latest || true

install:
  - true

script:
  - \set | grep "^[A-Z]"
  - echo docker build --pull --cache-from h2non/imaginary:latest --build-arg GOLANG="${GOVER}" --build-arg LIBVIPS_VERSION="${LIBVIPS}" --build-arg IMAGINARY_VERSION="${IMAGINARY_VERSION#v}" --tag h2non/imaginary:${IMAGINARY_VERSION} .
  - docker build --pull --cache-from h2non/imaginary:latest --build-arg GOLANG="${GOVER}" --build-arg LIBVIPS_VERSION="${LIBVIPS}" --build-arg IMAGINARY_VERSION="${IMAGINARY_VERSION#v}" --tag h2non/imaginary:${IMAGINARY_VERSION} .

before_deploy:
#  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
#  provider: script
#  script:
#    - docker tag h2non/imaginary:${IMAGINARY_VERSION} latest
#    - docker push h2non/imaginary:${IMAGINARY_VERSION}
#    - docker push h2non/imaginary:latest
#  on:
#    condition: "${TRAVIS_TAG} =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
